apiVersion: v1
kind: Service
metadata:
  name: bonita
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: bonita
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: bonita
  labels:
    app: bonita
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bonita
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bonita
        tier: frontend
    spec:
      containers:
      - image:  bonita:7.14.0
        name: bonita
        resources:
         requests:
          cpu: 250m
          memory: 256Mi
         limits:
          cpu: 512m
          memory: 512Mi
        env:
        - name: DB_VENDOR 
          value: postgres
        - name : DB_HOST
          value: bonita-postgres
        - name : DB_NAME
          value: bonita
        - name : DB_USER
          value: bonita
        - name: DB_PASS
          value: bpm
        - name: BIZ_DB_NAME
          value: business_data
        - name: BIZ_DB_USER
          value: business_data
        - name: BIZ_DB_PASS
          value: bpm
        - name: TENANT_LOGIN 
          value: tech_user
        - name: TENANT_PASSWORD
          value: secret
        - name: PLATFORM_LOGIN
          value: pfadmin
        - name: PLATFORM_PASSWORD
          value: pfsecret
        ports:
        - containerPort: 8080
          name: bonita
        volumeMounts:
          - name: secrets-store01-inline
            mountPath: "/mnt/secrets-store"
            readOnly: true
      volumes:
      - name: secrets-store01-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "azure-kvname-user-msi"