
apiVersion: v1
kind: Service
metadata:
  name: bonita-postgres
  labels:
    app: bonita
spec:
  ports:
    - port: 3306
  selector:
    app: bonita
    tier: postgres
  clusterIP: None
---
apiVersion: apps/v1 # for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: bonita-postgres
  labels:
    app: bonita
    tier: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
     app: bonita
     tier: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bonita
        tier: postgres
    spec:
      containers:
      - image: bonitasoft/bonita-postgres:12.6
        name: postgres
        resources:
         requests:
          cpu: 100m
          memory: 128Mi
         limits:
          cpu: 250m
          memory: 256Mi
        env:
        - name: PGDATA
          valueFrom:
           fieldRef:
            apiVersion: v1
            fieldPath: metadata.name
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: akvsecrets
              key: passwordpostgresql
        ports:
        - containerPort: 3306
          name: postgres
        volumeMounts:
          - name: azure
            mountPath: /var/lib/postgresql/data
            subPathExpr: $(PGDATA)
          - name: secrets-store01-inline
            mountPath: "/mnt/secrets-store"
            readOnly: true
      volumes:
      - name: secrets-store01-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "azure-kvname-user-msi"
      - name: azure
        csi:
         driver: file.csi.azure.com
         readOnly: false
         volumeAttributes:
          secretName: azure-secret  # required
          shareName: dbfileshare  # required
          mountOptions: "dir_mode=0777,file_mode=0777,uid=1000,gid=1000,mfsymlinks,nobrl,cache=none"  # optional